version: '3'

services:
  backend:
    build: backend
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    volumes: 
      - redis-data:/data
    ports:
      - "6379:6379"
    
volumes:
  redis-data: